### ISSUE TITLE
Unnecessary `break`s.

### ISSUE THREAD

**Issue by anubhavp28** [gojek/darkroom#11]
https://github.com/gojek/darkroom/blob/982cf59c89fcba47b83afdf6abe8ecdbb80989b8/pkg/metrics/statsd_collector.go#L73

https://github.com/gojek/darkroom/blob/b920443b9764ba4f14dff581eca4ca6f21f6aa8a/pkg/processor/native/utils.go#L84

I guess, those breaks aren't really required.

**Comment by ajatprabha** [comment]
Yes, old habits die hard. You may remove them in a PR.

**Comment by adalberht** [comment]
Had some free time to do this, closing this issue.
Thanks @anubhavp28
