### ISSUE TITLE
Add Documentation to the project

### ISSUE THREAD

**Issue by ajatprabha** [gojek/darkroom#20]
##### What would you like to be added
I suggest adding separate documentation than what we have in README right now. It shall be generated from the source in `/docs` folder and hosted on GitHub pages on every CI release job.

##### Why is this needed
The code has good GoDoc coverage but there should be better documentation for the project showing how to use it. Users might not be familiar with all the features that Darkroom provides.

##### Comments
If you've other suggestions on how the docs should be built other than GH Pages, feel free to add them. Eg: [ReadTheDocs](https://readthedocs.org/), etc.

**Comment by kavishgambhir** [comment]
I would like to take up this issue. I would like to use Hugo as a static documentation generator from `/docs` folder which can be hosted on Github pages.

**Comment by ajatprabha** [comment]
@kavishgambhir Sounds good to me. Please make a landing page for docs first and then we can move ahead from there.

**Comment by kavishgambhir** [comment]
I am considering these two themes. Let me know if it suits the purpose
- [DocDock](https://themes.gohugo.io//theme/docdock/)
- [Kube](https://themes.gohugo.io/theme/kube/)

**Comment by baskarap** [comment]
I will be looking into above suggestion by this weekend.

**Comment by kavishgambhir** [comment]
After some digging, I found [Docusaurus](https://docusaurus.io/en/) to be a better option.
I am working on it right now

**Comment by kavishgambhir** [comment]
@baskarap I have deployed it to my fork's GitHub pages. If it looks ok, I can continue.

**Comment by baskarap** [comment]
@kavishgambhir It looks nice 🥇

**Comment by baskarap** [comment]
@ajatprabha closing this since it has been sorted out. feel free to reopen if it is necessary.
