### ISSUE TITLE
Add Progressive JPEG Support

### ISSUE THREAD

**Issue by adalberht** [gojek/darkroom#29]
##### What would you like to be added
Progressive JPEG support

##### Why is this needed
Currently Darkroom only supports Baseline JPEG which will load from top to bottom.
There exists Progressive JPEG format that loads from low quality to full quality like this:

![image](https://user-images.githubusercontent.com/25892469/63670979-8f3ddb00-c808-11e9-8014-b8425b7da133.png)

##### Comments

Refer to: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/

**Comment by baskarap** [comment]
Apparently, after checking gojek app's image loaders in both ios and android platforms, they seem to not support progressive jpeg loading right now. So if anyone have this requirement (which i think we will do eventually), feel free to reopen this issue and we can plan to support this.
