### ISSUE TITLE
Cleanup linter error

### ISSUE THREAD

**Issue by imjuanleonard** [gojek/darkroom#31]
It will be good to clean up these linter errors before it is causing problems. Also by following some simplification and code practice, it will make the code easier to maintain

##### What should be cleaned up or changed
from make lint
```
pkg/config/config.go:86:15: exported func Source returns unexported type *config.source, which can be annoying to use

pkg/processor/native/utils_test.go:162:41: exported func NewMockImage returns unexported type *native.mockImage, which can be annoying to use

pkg/service/manipulator.go:166:52: exported func NewManipulator returns unexported type *service.manipulator, which can be annoying to use

pkg/processor/native/encoder.go:79:1: comment on exported method Encoders.Options should be of the form "Options ..."

```

from golangci-lint
```
pkg/processor/native/processor_test.go:21:2: `badImage` is unused (structcheck)
	badImage      image.Image
	^
pkg/processor/native/processor_test.go:181:11: ineffectual assignment to `err` (ineffassign)
		img, _, err := s.processor.Decode(file)
		        ^
internal/handler/ping.go:12:3: S1023: redundant `return` statement (gosimple)
		return
		^
pkg/server/api.go:63:2: S1005: '_ = <-ch' can be simplified to '<-ch' (gosimple)
	_ = <-sig
	^
pkg/service/manipulator_test.go:132:27: S1019: should use make([]byte, 10) instead (gosimple)
		ImageData: make([]byte, 10, 10),
```

To Cleanup makefile
```
-  We don't need to show the makefile command, can be achieved by using silent @
```

##### Provide any links for context
- https://github.com/golangci/golangci-lint 

Do anyone want to pick this up or Can I pick this up?

**Comment by ajatprabha** [comment]
Thanks, @imjuanleonard for pointing this out, feel free to fix this.

**Comment by baskarap** [comment]
Thanks, feel free to pick this up.

**Comment by adalberht** [comment]
@baskarap regarding this, do we want to be strict and follow golint? If yes, to prevent this from happening again, maybe it would be nice to let golint return non-zero code when there's linter error so that the CI fails? wdyt?

**Comment by baskarap** [comment]
Sure, making it to return non-zero code can be done as well.

**Comment by imjuanleonard** [comment]
Sure, will pick by today. Noted, will add the lint to the pipeline

**Comment by imjuanleonard** [comment]
Hi, after checking several blog and communities about linter in pipeline convention.

Linter will make the pipeline slower, and some people still argue it is not a good practice to add linter in gitlab. The suggestion was to put any code-cleaner task inside the git hooks or the IDE itself. So it will always happen and not slowing.

What do you guys think?

**Comment by adalberht** [comment]
@imjuanleonard IMO making it in the pipeline is still fine because the thing with Git hook and IDE task is that it's local and need some setup on the user side and we can't control that. It would be nice to make it in the pipeline to make sure that the style is consistent across the repository with different contributors since we can't catch every inconsistency manually
