### ISSUE TITLE
Failing Deployment

### ISSUE THREAD

**Issue by imjuanleonard** [gojek/darkroom#34]
**Which jobs are failing**:
- The deploy part in the master branch

**Since when has it been failing**:
- Since add documentation commit `https://github.com/gojek/darkroom/commit/21c61f2d1e3f292ff4750f7e8483e83c5c19cd13`

- This is the job 
`https://travis-ci.org/gojek/darkroom/builds/577348025?utm_source=github_status&utm_medium=notification`

On `deploying application` stage

**Reason for failure**:
- Git exit with non-zero error code
- It happens because the runner doesn't have push access to the repository

```
nothing to commit, working tree clean
remote: Invalid username or password.
fatal: Authentication failed for 'https://irfn@github.com/gojek/darkroom.git/'
Error: Git push failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Anything else we need to know**:
- Is it really necessary to push to publish-gh-pages branch?
- If it is, then I would recommend giving the runner push access using a new ssh credentials, we can use similar to this gitlab documentation https://docs.gitlab.com/ee/ci/ssh_keys/

**Comment by ajatprabha** [comment]
travis-ci.org builds should be disabled, travis-ci.com builds pass successfully. Already informed @baskarap

**Comment by imjuanleonard** [comment]
Awesome, I only know that .org is for free and .com is for paid
what the difference between travis-ci.org and travis-ci.com builds actually?
Why is it passing in .com but not passing in .org?

**Comment by ajatprabha** [comment]
Travis had two versions i.e. Enterprise and Community, they are combining both into one now. There's no actual difference between builds. Currently only .com version has secrets not the .org version, hence the failing builds.

**Comment by imjuanleonard** [comment]
cool, closing the comments
