### ISSUE TITLE
[Request] Add support for fit=scale

### ISSUE THREAD

**Issue by ajesh-n** [gojek/darkroom#39]
##### What would you like to be added
fit=scale support 
Scales the image to fit the constraining dimensions exactly. The resulting image will fill the dimensions, and will not maintain the aspect ratio of the input image.

##### Why is this needed
To get resized images with fit type scale.

**Comment by baskarap** [comment]
Thanks, I will pick this up.

**Comment by baskarap** [comment]
Added here: https://github.com/gojek/darkroom/pull/41
