### ISSUE TITLE
Add ability to do byte range request to storage

### ISSUE THREAD

**Issue by anggiaj** [gojek/darkroom#50]
##### What would you like to be added

Darkroom storage HTTP byte-range request support

##### Why is this needed

When utilizing Google CDN in front of an app (which use darkroom), and the app has a large file (>= 10MB), we can forward Google CDN request to "end storage" (e.g: s3, CloudFront, etc), and forwarding response that came from "end storage" to Google CDN

##### Comments

PR: https://github.com/gojek/darkroom/pull/49

**Comment by ajatprabha** [comment]
Closing this as #49 is merged.
