### ISSUE TITLE
Add Support for Prometheus

### ISSUE THREAD

**Issue by imjuanleonard** [gojek/darkroom#55]
##### What would you like to be added

Add support for publishing metrics to Prometheus.

##### Why is this needed
It will be fantastic when the metrics not tied up to spikes, even better when we have Prometheus support for its better integration in other CNCF projects like Kubernetes.

##### Comments

-> Need to design a metrics RFC for supporting prometheus

**Comment by ajatprabha** [comment]
#56 PR is in progress to implement this.
